#
#This will update and install only the security updates
#
---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Make a copy of security repos
    shell: cat /etc/apt/sources.list|grep secu >/etc/apt/security.sources.list

  - name: Update cache
    apt: update_cache=yes

  - name: Install security updates
    shell: apt-get upgrade -oDir::Etc::SourceList=/etc/apt/security.sources.list --force-yes -y