---
hosts: all
become: yes
remote_user: root

tasks:
  - include_vars: users.yml

  - name: Add users | create users, shell, home dirs
    user: name={{ item.username }} shell=/bin/bash createhome=yes comment='create with ansible'
    with_items: '{{users}}'


  - name: generate new key for current user
    user:
      name: "{{item.username}}"
      password: "{{item.password | password_hash('sha512')}}"
      update_password: always
      generate_ssh_key: yes
      ssh_key_passphrase: "{{item.passphrase}}"
      ssh_key_bits: 2048
    with_items: '{{users}}'


  - name: set authorized_key
    copy:
      src: /home/{{ item.username }}/.ssh/id_rsa.pub
      dest: /home/{{ item.username }}/.ssh/authorized_keys
      mode: '0600'
      remote_src: yes
      owner: "{{item.username}}"
      group: "{{item.username}}"
    with_item: "{{ users }}"



  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present"
      validate: 'visudo -cf %s'
    with_items: '{{users}}'




  - name: Expiring password for user {{item.username}}
    shell: chage -d 90 {{item.username}}
    with_items: '{{users}}'



  - name: Create sudoers
    template:
      src: sudoers.d.j2
      dest: "/etc/sudoers.d/{{ sudoers_filename }}"
      mode: 0440
      owner: root
      group: root
      validate: "/usr/sbin/visudo -cf %s"
